package org.eaticious.greenlicious;

public enum ApplianceType {
	
	STOVETOP_ELECTRIC, STOVETOP_CERAMIC, STOVETOP_INDUCTION, STOVETOP_GAS,
	
	OVEN_ELECTRIC, OVEN_GAS,
	
	RICECOOKER, WATERCOOKER,
	
	FRIDGE_CLASS_AAA, FRIDGE_CLASS_AA, FRIDGE_CLASS_A, FRIDGE_CLASS_B

}
